wip

diff --git a/bin/triton-bootstrap b/bin/triton-bootstrap
--- a/bin/triton-bootstrap
+++ b/bin/triton-bootstrap
@@ -14,7 +14,8 @@ export MYCPUS=$(($MYCPUS>1?$MYCPUS:1))
 export COUCHBASE_NS_SERVER_VM_EXTRA_ARGS=$(printf '["+S", "%s"]' $MYCPUS)
 export ERL_AFLAGS="+S $MYCPUS"
 export GOMAXPROCS=$MYCPUS
-export MYMEMORY=$(echo "$MYMEMORY*.80" | bc | grep -o "^[^\.]*")
+export MYMEMORY=$((($MYMEMORY/10)*8))
+export BUCKET=$2
 
 installed ()
 {
@@ -49,19 +50,42 @@ while [ $COUCHBASERESPONSIVE != 1 ]; do
     if [ $? -eq 0 ]; then
         let COUCHBASERESPONSIVE=1
     fi
+
+    # test the alternate u/p
+    couchbase-cli server-info -c 127.0.0.1:8091 -u Administrator -p password &> /dev/null
+    if [ $? -eq 0 ]; then
+        let COUCHBASERESPONSIVE=1
+    fi
 done
 sleep 3
 
 # it's responsive, is it already configured?
-couchbase-cli cluster-info -c 127.0.0.1:8091 -u Administrator -p password &> /dev/null
+couchbase-cli server-list -c 127.0.0.1:8091 -u Administrator -p password &> /dev/null
 if [ $? -eq 0 ]; then
     echo
     echo '#'
-    echo '# Already installed and joined to cluster...'
+    echo '# Already joined to cluster...'
     echo '#'
     installed
 
     exit
+fi
+
+echo
+echo '#'
+echo '# Checking Consul availability'
+echo '#'
+
+curl http://consul:8500/v1/agent/services &> /dev/null
+if [ $? -ne 0 ]
+then
+    echo '#'
+    echo '# Consul is required, but unreachable'
+    echo '#'
+    exit
+else
+    echo '# Consul instance found and responsive'
+    echo '#'
 fi
 
 echo
@@ -74,49 +98,79 @@ echo '#'
     --node-init-index-path=/opt/couchbase/var/lib/couchbase/data \
     --node-init-hostname=$MYIPPRIVATE
 
-if [ "$1" = 'couchbase-server' ]
+if [ "$1" = 'bootstrap' ]
 then
     echo '#'
     echo '# Bootstrapping cluster'
     echo '#'
-    
+
     /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 -u access -p password \
         --cluster-init-username=Administrator \
         --cluster-init-password=password \
         --cluster-init-port=8091 \
         --cluster-init-ramsize=$MYMEMORY
-    
+
     /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.01:8091 -u Administrator -p password \
-        --bucket=benchmark \
-        --bucket-type=$BUCKET \
+        --bucket=$BUCKET \
+        --bucket-type=couchbase \
         --bucket-ramsize=$MYMEMORY \
         --bucket-replica=1
 else
     echo '#'
     echo '# Looking for an existing cluster'
     echo '#'
-    
-    curl -v http://consul:8500/v1/catalog/service/couchbase | json -aH ServiceAddress
-    
+
+    CLUSTERIP=$(curl -sL http://consul:8500/v1/catalog/service/couchbase | json -aH ServiceAddress | head -1)
+
     echo '#'
-    echo '# Joining cluster'
+    echo '# Joining cluster...'
     echo '#'
-    
-    curl -i -u Administrator:password \
-        http://192.168.129.188:8091/controller/addNode \
-        -d "hostname=$(ip addr show eth0 | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')&user=admin&password=password"
-    
+
+    COUCHBASERESPONSIVE=0
+    while [ $COUCHBASERESPONSIVE != 1 ]; do
+        echo -n '.'
+
+        curl -s -i -u Administrator:password \
+            "http://$CLUSTERIP:8091/controller/addNode" \
+            -d "hostname=$(ip addr show eth0 | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')&user=admin&password=password"
+        if [ $? -eq 0 ]; then
+            let COUCHBASERESPONSIVE=1
+        fi
+
+        sleep .7
+    done
+
+
+    echo
     echo '#'
     echo '# Rebalancing cluster'
     echo '#'
-    
+
     couchbase-cli rebalance -c 127.0.0.1:8091 -u Administrator -p password
-    
-    echo '#'
-    echo '# Registering service instance'
-    echo '#'
-    
-    curl http://165.225.190.200:8500/v1/agent/service/register -d "$(printf '{"ID":"couchbase-%s","Name":"couchbase","Address":"%s"}' $MYIPPRIVATE $MYIPPRIVATE)"
-    
-    installed
 fi
+
+
+echo
+echo '#'
+echo '# Confirming cluster status...'
+echo '#'
+
+COUCHBASERESPONSIVE=0
+while [ $COUCHBASERESPONSIVE != 1 ]; do
+    echo -n '.'
+    sleep .7
+
+    couchbase-cli server-list -c 127.0.0.1:8091 -u Administrator -p password
+    if [ $? -eq 0 ]; then
+        let COUCHBASERESPONSIVE=1
+    fi
+done
+
+echo
+echo '#'
+echo '# Registering service instance'
+echo '#'
+
+curl http://consul:8500/v1/agent/service/register -d "$(printf '{"ID":"couchbase-%s","Name":"couchbase","Address":"%s"}' $MYIPPRIVATE $MYIPPRIVATE)"
+
+installed
